#!/bin/sh
chosen=$(dmenu -i -l 20 < ~/.local/share/kaomoji | sed "s/ .*//")
[ "$chosen" ] || exit
[ "$1" ] && xdotool key Shift+Insert || $(echo "$chosen" | tr -d '\n' | xclip -selection clipboard; notify-send "'$chosen' copied to clipboard.")
